### ISSUE TITLE
Прошу помощи.

### ISSUE THREAD

**Issue by meta11st87** [DieMetRik/mercury_esphome#1]
Приветствую. Спасибо за инфу по подключению.
Пытаюсь повторить ваше проект, но маленько на другом железе и ничего не выходит(

Использую плату nodemcu esp32(потому что была в наличии) и плату ttl rs485, вроде как называется XY-017
Управление потоком аппаратное, поэтому вроде как не нужно ничего на плату подключать, кроме rt/tx и питания.
Схема подключения:
![esp](https://user-images.githubusercontent.com/56351037/161149150-29d13383-a06f-42b9-b185-95ce5184a837.jpg)

Конфиг до раздела сенсоров:
```
esphome:
  name: mercury
  includes:
    - /config/esphome/mercury/mercury-200.02.h #Указываем свой путь до файла

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:


# Enable Home Assistant API
api:
  password: !secret ha_password


ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.150
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "mercury-206"
    password: !secret ap_password

captive_portal:


uart:
  id: uart_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
```

Тх моргают, но счётчик не отвечает, рх молчит. Плату запитывал тестово от повербанка.
Собственно, ряд вопросов:
У вас какой модификации счётчик? У меня RN, вроде как они отличаются, что какому-то счётчику нужно доппитание, а какому-то нет.

Адрес счётчика как правильно выставить? У меня номер счётчика 12343320 -18. Если ставлю 320 то результата положительного нет. Вроде как эти счётчики должны на 0 адрес отвечать, если в шине он один, но это тоже не работает.

Вроде все варианты уже перепробовал, но не взлетает.

Может у вас есть мысли ЧЯДНТ?

upd. Пробовал на контакты счётчика, которые рядом с rs расположены, и которые промаркированы как U и земля, подать 5в, судя по той инфе, которая нашлась в интернете это питание rs-интерфейса - не помогло.
